### ISSUE TITLE
[Bug]: how to add a admin users?

### ISSUE THREAD

**Issue by fifysky** [RansomLook/RansomLook#429]
### What happened?

I add a users in config/generic.json.But I can't login.Can you tell me how to use admin ui?

### Relevant log output

```shell
"_notes": {
        "malpedia": "malpedia apikey",
        "email": "Email configuration",
        "email_smtp_auth": "SSL configuration for email",
        "rocketchat": "Informatin about rocketckat",
        "twitter": "Allow to post new item to Twitter",
        "website_listen_ip": "IP Flask will listen on. Defaults to 0.0.0.0, meaning all interfaces.",
        "website_listen_port": "Port Flask will listen on.",
        "thread": "Number of PW instances to run",
        "users":  "{admin:123456}",
```

**Comment by FafnerKeyZee** [comment]
Hello,

Once you added your user you have to restart ransomlook, then using your browser, go to https://yourinstance.tld/login page

Br,

**Comment by nickorlabs** [comment]
Would be very helpful if this was explained in the readme spent the last few days chasing my tail on how to add telegram channels etc.  If you have anything started, I would be happy to start reviewing and provide feedback updates.

**Comment by FafnerKeyZee** [comment]
Hey,
I know the doc isn't very uselful, I added a task in the project to create it.

To add a chan; this channel must be visible for everyone, so no invit link and no need to use the app. For exemple this chan will be ok for RL.
https://t.me/Noname05716Eng 
If you click on preview you should be able to see the content of the chan.

Then go to 
https://yourinstance/admin/add
Select : Telegram
Group: Name of the Chan (so Noname05716Eng in our case)
URL: https://t.me/Noname05716Eng

![image](https://github.com/user-attachments/assets/50833147-10e5-49e5-b87b-7649b96a6842)


This part will me change for next release in order to make it easier with only the name of the group...

**Comment by nickorlabs** [comment]
Yeah took me a minute to find the login page, this issue helped LOL 

Looking forward to the next release!!  Really love this project, saw rocket chat options, seeing AID Locker I think might have moved to Element chat; wondered about Element API scraping being added.

Let me know if there is anything I can do to help!

**Comment by nickorlabs** [comment]
Also wanted to add this

I had to have the user look like this above notes to get it to work, so wanted to share my finding/ outcome.
 
i.e.
    "misp": {
        "enable": false,
        "url": "",
        "apikey": "",
        "tls_verify": true,
        "publish": true
    },
"users":  {"admin": "123456"},
